# Generated by Django 4.1.7 on 2023-04-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='mock_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Content', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
