# Generated by Django 4.1.7 on 2023-04-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0003_mock_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
